require('./ship_test');
require('./asteroid_test');
require('./laser_test');
require('./mine_test');
require('./shield_test');
require('./spaceTime_test');
require('./alienLaser_test');
require('./alien_test');
require('./game_test');